# Generated by Django 5.1.6 on 2025-07-09 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='图标')),
                ('weight', models.IntegerField(default=0, verbose_name='权重')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'nav_category',
                'ordering': ['-weight'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='网站名称')),
                ('url', models.URLField(verbose_name='网址')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('weight', models.IntegerField(default=0, verbose_name='权重')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='图标')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '链接',
                'verbose_name_plural': '链接',
                'db_table': 'nav_link',
                'ordering': ['-weight'],
            },
        ),
    ]
